// -------------------------------------------------------------------
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<title>Untitled Document</title>");
document.writeln("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\">");
document.writeln("</head>");
document.writeln("");
document.writeln("<body bgcolor=\"#FFFFFF\" text=\"#000000\">");
document.writeln("	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
document.writeln("	<tr bgcolor=\"#DCDCDC\"><td height=\"16\" class=z>&nbsp;<font color=\"#565656\">");
document.writeln("	<a href=\"/\" target=\"_blank\"><font color=\"#565656\">首&nbsp页</font></a>|");
document.writeln("	<a href=\"/wcm/caijing/\" target=\"_blank\"><font color=\"#565656\">财&nbsp经</font></a>|");
document.writeln("	<a href=\"/sports/\" target=\"_blank\"><font color=\"#565656\">体&nbsp育</font></a>|");
document.writeln("	<a href=\"/music/\" target=\"_blank\"><font color=\"#565656\">调&nbsp频</font></a>|");
document.writeln("	<a href=\"/library/\" target=\"_blank\"><font color=\"#565656\">书&nbsp院</font></a>|");
document.writeln("	<a href=\"/travel/\" target=\"_blank\"><font color=\"#565656\">旅&nbsp游</font></a>|");
document.writeln("	<a href=\"/car/\" target=\"_blank\"><font color=\"#565656\">汽&nbsp车</font></a>|");
document.writeln("	<a href=\"/military/\" target=\"_blank\"><font color=\"#565656\">军&nbsp事</font></a>|");
document.writeln("	<a href=\"/folk/\" target=\"_blank\"><font color=\"#565656\">民&nbsp族</font></a>|");
document.writeln("	<a href=\"http://www.nihaotw.com/\" target=\"_blank\"><font color=\"#565656\">台&nbsp湾</font></a>|");
document.writeln("	<a href=\"http://211.101.182.9:8888/index.asp\" target=\"_blank\"><font color=\"#565656\">短&nbsp信</font></a>|");
document.writeln("	<a href=\"http://search.cnradio.com.cn\" target=\"_blank\"><font color=\"#565656\">搜&nbsp索</font></a>|");
document.writeln("	<a href=\"/home/guanggao/index.html\" target=\"_blank\"><font color=\"#565656\">广&nbsp告</font></a>&nbsp;&nbsp;");
document.writeln("	</font></td></tr>");
document.writeln("	</table>");
document.writeln("</body>");
document.writeln("</html>");
// -------------------------------------------------------------------




